/* Generated by Together */

package us.mn.state.health.model.common;

import java.io.Serializable;
import java.util.Date;

public class Organization implements Serializable {
    /**
     * @clientCardinality 1
     * @supplierCardinality 0..*
     */
    private OrgBudget orgBudget;
    private String deptIdName;
    private String changedBy;
    private String orgFormalName;
    private String deptIdCode;
    private Date changedDate;
    private String comments;
    private Date orgEndDate;
    private Date orgEffectiveDate;
    private Date insertionDate;
    private String insertedBy;
    private String orgShortName;
    private String orgName;
    private String orgType;
    private String orgCode;
    private Long orgId;
    private int version;

    public String getDeptIdName() {
        return deptIdName;
    }

    public void setDeptIdName(String deptIdName) {
        this.deptIdName = deptIdName;
    }

    public String getChangedBy() {
        return changedBy;
    }

    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy;
    }

    public String getOrgFormalName() {
        return orgFormalName;
    }

    public void setOrgFormalName(String orgFormalName) {
        this.orgFormalName = orgFormalName;
    }

    public String getDeptIdCode() {
        return deptIdCode;
    }

    public void setDeptIdCode(String deptIdCode) {
        this.deptIdCode = deptIdCode;
    }

    public Date getChangedDate() {
        return changedDate;
    }

    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Date getOrgEndDate() {
        return orgEndDate;
    }

    public void setOrgEndDate(Date orgEndDate) {
        this.orgEndDate = orgEndDate;
    }

    public Date getOrgEffectiveDate() {
        return orgEffectiveDate;
    }

    public void setOrgEffectiveDate(Date orgEffectiveDate) {
        this.orgEffectiveDate = orgEffectiveDate;
    }

    public Date getInsertionDate() {
        return insertionDate;
    }

    public void setInsertionDate(Date insertionDate) {
        this.insertionDate = insertionDate;
    }

    public String getInsertedBy() {
        return insertedBy;
    }

    public void setInsertedBy(String insertedBy) {
        this.insertedBy = insertedBy;
    }

    public String getOrgShortName() {
        return orgShortName;
    }

    public void setOrgShortName(String orgShortName) {
        this.orgShortName = orgShortName;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgType() {
        return orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }


    public void setVersion(int version) {
        this.version = version;
    }


    public int getVersion() {
        return version;
    }


    public void setOrgBudget(OrgBudget orgBudget) {
        this.orgBudget = orgBudget;
    }


    public OrgBudget getOrgBudget() {
        return orgBudget;
    }
}
