UPDATE PRIORITY_TBL p SET p.PRIORITY_NAME = 'Second day' WHERE p.PRIORITY_CODE = 'LOW';
UPDATE PRIORITY_TBL p SET p.PRIORITY_NAME = 'Normal (ground)' WHERE p.PRIORITY_CODE = 'NORM';
UPDATE PRIORITY_TBL p SET p.PRIORITY_NAME = 'Next day' WHERE p.PRIORITY_CODE = 'HIGH';

UPDATE MATERIALS_REQUEST_TBL SET PRIORITY_ID = 62233 WHERE PRIORITY_ID = 62234;
