REM INSERTING into APPLICATION_CONFIG_ITEM_TBL
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Parit Computer Purchaser','7023',991,'PARITCOMPUTERSHIPTO',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Notification','<!--<font size="6" color=red><blink>testing</blink><font>
-->',666773,'MESSAGE_NOTIFY_MAINMENU',155);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Notification','<small><p/><b>INFORMATION ONLY:<br/>
To purchase IT items please submit a Helpdesk ticket . MDH is transitioning to a new IT approval process, and MN.iT staff will contact you on IT purchase requests. This does not include telecommunications equipment.  FFM Buyers no longer process IT purchases directly in PRISM before ISTM approval.     <a href="http://fyi.health.state.mn.us/open/helpdesk">To Help desk</a>
</small></b>
',666772,'MESSAGE_NOTIFY_LOGIN',101);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Stock Item Lucene Index','/export/project/prism/LuceneIndexes/stockItemIndex',70896,'SIIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Request Line Item Lucene Index','/export/project/prism/LuceneIndexes/requestLineItemIndex',70898,'RLIIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Purchase Item Lucene Index','/export/project/prism/LuceneIndexes/purchaseItemIndex',70899,'PIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Request Lucene Index','/export/project/prism/LuceneIndexes/requestIndex',70900,'RIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The data directory of Rules4J','/var/lib/tomcat5.5/appdata/prism//BusinessRules',70901,'R4JP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Orders Lucene Index','/export/project/prism/LuceneIndexes/orderIndex',70902,'OLIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the Fixed and Sensitive Asset Lucene Index','/export/project/prism/LuceneIndexes/assetIndex',70904,'ALIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The directory of the OrderLineItems Lucene Index','/export/project/prism/LuceneIndexes/orderLineItemIndex',163634,'OLIIP',1);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the OrderLineItems Lucene Index','/export/project/prism/tempLuceneIndexes/orderLineItemIndex',170178,'TOLIIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Fixed and Sensitive Assets Index','/export/project/prism/tempLuceneIndexes/assetIndex',170179,'TALIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Stock Item Lucene Index','/export/project/prism/tempLuceneIndexes/stockItemIndex',170180,'TSIIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Request Line Item Lucene Index','/export/project/prism/tempLuceneIndexes/requestLineItemIndex',170181,'TRLIIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Request Lucene Index','/export/project/prism/tempLuceneIndexes/requestIndex',170182,'TRIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Orders Lucene Index','/export/project/prism/tempLuceneIndexes/orderIndex',170183,'TOLIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The temp directory of the Purchase Item Lucene Index','/export/project/prism/tempLuceneIndexes/purchaseItemIndex',170184,'TPIP',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Number of days until the request line items that need approval are automatically cancelled','17',689791,'DAYS_TO_CANCEL',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Number of days until the request line items that need approval trigger a reminder email','10',689792,'DAYS_TO_WARN',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'source of group membership information {''ORACLE_TABLES'' | ''MS_ACTIVE_DIRECTORY''}','ORACLE_TABLES',689793,'RETRIEVE_GROUP_MEMBERSHIP_FROM',0);
Insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'Budget Builder Link','<br/><a href="https://inside.mn.gov/sites/MDH/temporary/fy17MNITBudgetBuilders/Forms/AllItems.aspx" target="Contract">Budget Builder</a>',689795,'BUDGET_BUILDER_LINK',0);

insert into APPLICATION_CONFIG_ITEM_TBL (APP_ID,CONFIG_ITEM_NAME,CONFIG_ITEM_VALUE,APP_CONFIG_ITEM_ID,CONFIG_ITEM_CODE,VERSION) values (70895,'The URL of the authentication server','https://appsint.health.state.mn.us/java-ldap-auth/people/',689795,'AUTHENTICATION_SERVER_2',0);