ALTER TABLE
    PRISM_OWNER.ITEM_TBL ADD (DELIVERY_DETAIL_ID NUMBER(22));
ALTER TABLE
    PRISM_OWNER.ITEM_TBL ADD CONSTRAINT ITEM_DELIVERY_DTL_FK FOREIGN KEY (DELIVERY_DETAIL_ID)
    REFERENCES PRISM_OWNER.MATERIALS_REQ_DELIVERY_DTL_TBL (DELIVERY_DETAIL_ID)
ON
DELETE
    SET NULL